version: 0.2

env:
  variables:
    HOME: "/home/robotester"

phases:
  install:
    commands:
      - cd app & python3 -m venv venv
      - . venv/bin/activate
      - pip install --upgrade RESTinstance    
      
  build:
    commands:
      - cd app/tests && echo Run tests..
      - robot --outputdir result -L TRACE  -x integration_test.xml test.robot
artifacts:
  discard-paths: yes 
  base-directory: 'app'     
  files:
    - '**/*'
  name: $PipelineName-IntegrationTest-$(date +%Y-%m-%d)
  
reports:
  my-new-group: 
    base-directory: 'app/tests/result' 
    files:
      - 'integration_test.xml'
      - 'log.html'
    discard-paths: yes
