Description: Enables crosss-account CI/CD by creating required role in environment accounts (dev, test, prod)

Parameters:
  DevOpsAccountId:
    Type: Number
    Description: The AWS account id that holds the pipelines


Resources: 
  CloudformationRole: 
    Properties: 
      AssumeRolePolicyDocument: 
        Statement: 
          - 
            Action: 
              - "sts:AssumeRole"
            Effect: Allow
            Principal: 
              AWS: 
                - !Ref DevOpsAccountId
              Service: 
                - codepipeline.amazonaws.com
                - codedeploy.amazonaws.com
                - cloudformation.amazonaws.com
        Version: 2012-10-17
      Policies: 
        - 
          PolicyDocument: 
            Statement: 
              - 
                Action: 
                  - "s3:*"
                  - "rds:*"
                  - "waf-regional:*"
                  - "apigateway:*"
                  - "events:*"
                  - "sns:*"
                  - "kms:Decrypt"
                  - "iam:*"
                  - "cloudformation:*"
                  - "cloudfront:*"
                  - "lambda:*"
                  - "secretsmanager:*"
                  - "ec2:*"
                  - "cognito-idp:*"
                  - "cognito-identity:*"
                Effect: Allow
                Resource: "*"
              - 
                Action: 
                  - "kms:*"
                Effect: Allow
                Resource: !Join ['',['arn:aws:kms:', !Ref "AWS::Region", ':', !Ref DevOpsAccountId, ':key/*']]
            Version: 2012-10-17
          PolicyName: PipelineSupportPolicy
      RoleName: PipelineSupportRole
    Type: "AWS::IAM::Role"


Outputs:
  CloudformationRole:
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", CloudformationRole ] ]
    Value: !GetAtt CloudformationRole.Arn